<template>
  <AppLayout>
    <div class="min-h-screen flex flex-col">
      <div class="flex-1 px-3 sm:px-4 lg:px-8 py-4 sm:py-6 lg:py-8">
        <div class="mb-4 sm:mb-6 lg:mb-8"><div class="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3 sm:gap-4"><div><h1 class="text-2xl sm:text-3xl font-bold text-gray-900">Fee Collection Summary Report</h1><p class="mt-1 sm:mt-2 text-xs sm:text-sm text-gray-600">View auto-generated fee collection summaries based on vouchers</p></div></div></div>
        <div class="bg-white rounded-lg sm:rounded-xl shadow-md p-4 sm:p-6 mb-4 sm:mb-6"><div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3 sm:gap-4"><div><Input v-model="filters.search" placeholder="Search branch or year..." @input="searchDebounced" class="w-full text-sm" /></div><div><select v-model="filters.branch_id" @change="loadData" class="w-full border-gray-300 focus:border-blue-500 focus:ring-blue-500 rounded-md shadow-sm text-sm"><option value="">All Branches</option><option v-for="branch in branches" :key="branch.id" :value="branch.id">{{ branch.branch_name }}</option></select></div><div><select v-model="filters.month" @change="loadData" class="w-full border-gray-300 focus:border-blue-500 focus:ring-blue-500 rounded-md shadow-sm text-sm"><option value="">All Months</option><option v-for="m in 12" :key="m" :value="m">{{ new Date(0, m - 1).toLocaleString('default', { month: 'long' }) }}</option></select></div><div><Button variant="secondary" @click="resetFilters" class="w-full shadow-sm hover:shadow-md transition-all duration-200 text-sm">Reset Filters</Button></div></div></div>
        <div class="hidden md:block bg-white rounded-lg sm:rounded-xl shadow-lg overflow-hidden">
          <div class="flex flex-col sm:flex-row items-start sm:items-center justify-between px-4 sm:px-6 py-3 sm:py-4 border-b border-gray-200 bg-gray-50 gap-3"><div class="flex items-center gap-2 sm:gap-3 w-full sm:w-auto"><span class="text-xs sm:text-sm text-gray-700">Show</span><select v-model="perPage" @change="changePerPage" class="px-3 sm:px-6 py-1.5 border border-gray-300 rounded-lg shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-500 text-xs sm:text-sm"><option value="10">10</option><option value="25">25</option><option value="50">50</option><option value="100">100</option></select><span class="text-xs sm:text-sm text-gray-700">entries</span></div><div class="w-full sm:w-64"><div class="relative"><input v-model="tableSearch" @input="tableSearchDebounced" type="text" placeholder="Search in table..." class="w-full pl-9 sm:pl-10 pr-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 text-xs sm:text-sm" /><svg class="absolute left-2.5 sm:left-3 top-2.5 h-4 w-4 sm:h-5 sm:w-5 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"/></svg></div></div></div>
          <div class="overflow-x-auto"><table id="fee-collection-summaries-table" class="min-w-full divide-y divide-gray-200"><thead class="bg-gradient-to-r from-indigo-50 to-blue-50"><tr><th class="px-3 sm:px-6 py-3 sm:py-4 text-xs font-semibold text-gray-700 uppercase tracking-wider text-center">#</th><th class="px-3 sm:px-6 py-3 sm:py-4 text-xs font-semibold text-gray-700 uppercase tracking-wider text-center">Branch</th><th class="px-3 sm:px-6 py-3 sm:py-4 text-xs font-semibold text-gray-700 uppercase tracking-wider text-center">Academic Year</th><th class="px-3 sm:px-6 py-3 sm:py-4 text-xs font-semibold text-gray-700 uppercase tracking-wider text-center">Month/Year</th><th class="px-3 sm:px-6 py-3 sm:py-4 text-xs font-semibold text-gray-700 uppercase tracking-wider text-center">Total Collected</th><th class="px-3 sm:px-6 py-3 sm:py-4 text-xs font-semibold text-gray-700 uppercase tracking-wider text-center">Total Pending</th><th class="px-3 sm:px-6 py-3 sm:py-4 text-xs font-semibold text-gray-700 uppercase tracking-wider text-center">Total Students</th><th class="px-3 sm:px-6 py-3 sm:py-4 text-xs font-semibold text-gray-700 uppercase tracking-wider text-center">Status</th></tr></thead><tbody class="bg-white text-center divide-y divide-gray-100"></tbody></table></div>
          <div class="flex flex-col sm:flex-row items-center justify-between px-4 sm:px-6 py-3 sm:py-4 border-t border-gray-200 bg-gray-50 gap-3 sm:gap-4"><div class="text-xs sm:text-sm text-gray-600" id="table-info"></div><div id="table-pagination"></div></div>
        </div>
        <div class="md:hidden space-y-3 sm:space-y-4">
          <div v-if="mobileLoading" class="flex items-center justify-center py-12 bg-white rounded-lg shadow"><div class="animate-spin rounded-full h-10 w-10 border-b-2 border-blue-600"></div></div>
          <div v-else-if="mobileItems.length === 0" class="text-center py-12 bg-white rounded-lg shadow"><svg class="mx-auto h-12 w-12 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 17v-2m3 2v-4m3 4v-6m2 10H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"/></svg><p class="mt-2 text-sm font-medium text-gray-500">No summaries found</p><p class="mt-1 text-xs text-gray-400">Try adjusting your filters</p></div>
          <div v-else v-for="(item, index) in mobileItems" :key="item.id" class="bg-white rounded-lg shadow-md overflow-hidden hover:shadow-lg transition-shadow"><div class="p-4"><div class="flex items-start justify-between mb-3"><div class="flex-1"><div class="flex items-center gap-2"><span class="text-xs font-semibold text-gray-500">#{{ mobileOffset + index + 1 }}</span><h3 class="text-base font-semibold text-gray-900">{{ item.branch_name ?? '-' }}</h3></div></div></div><div class="space-y-2 border-t border-gray-100 pt-3"><div class="flex items-center text-xs sm:text-sm"><svg class="w-4 h-4 text-gray-400 mr-2 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z"/></svg><span class="text-gray-600">{{ item.summary_month }}/{{ item.summary_year }}</span></div><div class="flex items-center text-xs sm:text-sm"><svg class="w-4 h-4 text-gray-400 mr-2 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z"/></svg><span class="text-gray-600">Collected: Rs. {{ Number(item.total_collected).toLocaleString() }}</span></div><div class="flex items-center text-xs sm:text-sm"><svg class="w-4 h-4 text-gray-400 mr-2 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"/></svg><span class="text-gray-600">Pending: Rs. {{ Number(item.total_pending).toLocaleString() }}</span></div></div></div></div>
        </div>
        <div v-if="mobileItems.length > 0" class="md:hidden mt-4 bg-white rounded-lg shadow p-3"><div class="flex items-center justify-between"><button @click="prevPage" :disabled="mobileCurrentPage === 1 || mobileLoading" class="px-4 py-2 text-sm font-medium border border-gray-300 rounded-lg disabled:opacity-50 disabled:cursor-not-allowed bg-white hover:bg-gray-50 transition-colors flex items-center gap-1"><svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7"/></svg>Previous</button><div class="text-center"><div class="text-sm font-medium text-gray-900">Page {{ mobileCurrentPage }} of {{ mobileTotalPages }}</div><div class="text-xs text-gray-500 mt-0.5">{{ mobileTotal }} total records</div></div><button @click="nextPage" :disabled="mobileCurrentPage === mobileTotalPages || mobileLoading" class="px-4 py-2 text-sm font-medium border border-gray-300 rounded-lg disabled:opacity-50 disabled:cursor-not-allowed bg-white hover:bg-gray-50 transition-colors flex items-center gap-1">Next<svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"/></svg></button></div></div>
      </div>

    </div>
  </AppLayout>
</template>
<script setup>
import { ref, onMounted, reactive } from 'vue'
import AppLayout from '@/Components/Layout/AppLayout.vue'
import Button from '@/Components/Common/Button.vue'
import Input from '@/Components/Forms/Input.vue'
import $ from 'jquery'
import 'datatables.net'
import axios from 'axios'
const props = defineProps({
  branches: Array
})

const tableSearch = ref(''), perPage = ref(10)
const mobileItems = ref([]), mobileLoading = ref(true), mobileCurrentPage = ref(1), mobileTotalPages = ref(1), mobileTotal = ref(0), mobileOffset = ref(0)
let table = null
const filters = reactive({ search: '', branch_id: '', month: '' })
const loadMobileData = async () => { mobileLoading.value = true; try { const params = { page: mobileCurrentPage.value, per_page: perPage.value, mobile: 1 }; if (filters.search) params.search = filters.search; if (filters.branch_id) params.branch_id = filters.branch_id; if (filters.month) params.month = filters.month; if (tableSearch.value) params.search = tableSearch.value; const response = await axios.get(route('fee-collection-summaries.index'), { params, headers: { 'X-Requested-With': 'XMLHttpRequest', 'Accept': 'application/json' } }); if (response.data?.data) { mobileItems.value = response.data.data; mobileCurrentPage.value = response.data.current_page || 1; mobileTotalPages.value = response.data.last_page || 1; mobileTotal.value = response.data.total || 0; mobileOffset.value = response.data.from ? response.data.from - 1 : 0 } else if (Array.isArray(response.data)) { mobileItems.value = response.data; mobileTotalPages.value = 1; mobileTotal.value = response.data.length; mobileOffset.value = 0 } } catch (e) { mobileItems.value = []; mobileTotal.value = 0 } finally { mobileLoading.value = false } }
onMounted(() => { loadMobileData(); table = $('#fee-collection-summaries-table').DataTable({ processing: true, serverSide: true, ajax: { url: route('fee-collection-summaries.index'), data: function (d) { d.search.value = filters.search || tableSearch.value; d.branch_id = filters.branch_id; d.month = filters.month; } }, columns: [ { data: 'DT_RowIndex', name: 'DT_RowIndex', orderable: false, searchable: false }, { data: 'branch_name', name: 'branch_name' }, { data: 'academic_year', name: 'academic_year', orderable: false, searchable: false }, { data: 'month_year', name: 'summary_month', orderable: false, searchable: false }, { data: 'total_collected', name: 'total_collected' }, { data: 'total_pending', name: 'total_pending' }, { data: 'total_students', name: 'total_students', orderable: false, searchable: false }, { data: 'action', name: 'action', orderable: false, searchable: false, className: 'text-center' } ], pageLength: 10, lengthMenu: [[10,25,50,100],[10,25,50,100]], order: [[1,'desc']], searching: true, info: true, responsive: true, dom: '<"flex items-center justify-between border-b border-gray-200"<"ml-auto"i>>rt<"flex items-center justify-between px-6 py-4 border-t border-gray-200"<"text-sm text-gray-600"i>p>', language: { emptyTable: '<div class="text-center py-12 text-gray-500"><svg class="mx-auto h-12 w-12 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 17v-2m3 2v-4m3 4v-6m2 10H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"/></svg><p class="mt-2 text-sm font-medium">No summaries found</p></div>', info: 'Showing _START_ to _END_ of _TOTAL_ entries', infoEmpty: 'Showing 0 to 0 of 0 entries', infoFiltered: '(filtered from _MAX_ total entries)', processing: '<div class="flex items-center justify-center py-8"><div class="animate-spin rounded-full h-10 w-10 border-b-2 border-blue-600"></div></div>', paginate: { first: '<svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 19l-7-7 7-7m8 14l-7-7 7-7"/></svg>', last: '<svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 5l7 7-7 7M5 5l7 7-7 7"/></svg>', next: '<svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"/></svg>', previous: '<svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7"/></svg>' } }, drawCallback: function () { $('#table-info').empty().append($('#fee-collection-summaries-table_info')); $('#table-pagination').empty().append($('#fee-collection-summaries-table_paginate')) } }) })
const prevPage = () => { if (mobileCurrentPage.value > 1 && !mobileLoading.value) { mobileCurrentPage.value--; loadMobileData(); window.scrollTo({ top: 0, behavior: 'smooth' }) } }
const nextPage = () => { if (mobileCurrentPage.value < mobileTotalPages.value && !mobileLoading.value) { mobileCurrentPage.value++; loadMobileData(); window.scrollTo({ top: 0, behavior: 'smooth' }) } }
let tableSearchTimeout = null; const tableSearchDebounced = () => { clearTimeout(tableSearchTimeout); tableSearchTimeout = setTimeout(() => loadData(), 500) }
let searchTimeout = null; const searchDebounced = () => { clearTimeout(searchTimeout); searchTimeout = setTimeout(() => loadData(), 500) }
const changePerPage = () => { if (table) table.page.len(perPage.value).draw(); mobileCurrentPage.value = 1; loadMobileData() }
const loadData = () => { if (table) table.ajax.reload(); mobileCurrentPage.value = 1; loadMobileData() }
const resetFilters = () => { filters.search = ''; filters.branch_id = ''; filters.month = ''; tableSearch.value = ''; loadData() }
</script>
<style scoped>
:deep(.dataTables_info) { font-size: 0.875rem; color: #4b5563; font-weight: 500; } :deep(.dataTables_paginate) { display: flex; justify-content: flex-end; gap: 0.25rem; flex-wrap: wrap; } :deep(.paginate_button) { padding: 0.5rem 0.75rem; font-size: 0.875rem; font-weight: 500; border: 1px solid #d1d5db; border-radius: 0.5rem; background: white; color: #374151; cursor: pointer; transition: all 0.2s; } :deep(.paginate_button:hover:not(.disabled)) { background: #f3f4f6; border-color: #9ca3af; } :deep(.paginate_button.current) { background: #2563eb; color: white; border-color: #2563eb; } :deep(.paginate_button.current:hover) { background: #1d4ed8; border-color: #1d4ed8; } :deep(.paginate_button.disabled) { opacity: 0.5; cursor: not-allowed; background: #f9fafb; } :deep(#fee-collection-summaries-table_info), :deep(#fee-collection-summaries-table_paginate) { display: none; } #table-info :deep(.dataTables_info), #table-pagination :deep(.dataTables_paginate) { display: block; } :deep(#fee-collection-summaries-table tbody td) { padding: 0.5rem 0.75rem; font-size: 0.875rem; } @media (min-width: 640px) { :deep(#fee-collection-summaries-table tbody td) { padding: 0.75rem 1.5rem; } } @media (max-width: 1024px) { :deep(#fee-collection-summaries-table) { font-size: 0.813rem; } :deep(#fee-collection-summaries-table th), :deep(#fee-collection-summaries-table td) { padding: 0.5rem; } }
</style>
